[build]

  base = "."
  
  command = """yarn workspace @certify-d/shared-ui install &&\
    yarn workspace @certify-d/kratos-helper install &&\
    nx run $PROJECT_NAME:build:production
    """

  ignore = "npx nx-ignore $PROJECT_NAME"

[build.environment]
  KRATOS_PUBLIC_URL = "not so secret :^)"
  NETLIFY_USE_YARN = "true" 

[context.production.environment]
  KRATOS_PUBLIC_URL = "not so secret"
