[build]
  ignore = "npx nx-ignore $PROJECT_NAME"

[build.environment]
  KRATOS_PUBLIC_URL = "not so secret :^)"
  NETLIFY_USE_YARN = "true" 

[context.production.environment]
  KRATOS_PUBLIC_URL = "not so secret"
