[build]
  command = "yarn nx build website"
  ignore = "yarn --cwd ../../ run nx-ignore website"
  publish = ".next"

[build.environment]
  KRATOS_PUBLIC_URL = "not so secret :^)"
  NETLIFY_USE_YARN = "true" 

[context.production.environment]
  KRATOS_PUBLIC_URL = "not so secret"
